services:
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    volumes:
      - /run/podman/podman.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped
    networks:
      - homepage-network
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      TZ: ${TZ:-UTC}
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_DOMAIN}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    volumes:
      - ./container-data/homepage-config:/app/config # Make sure your local config directory exists
    networks:
      - homepage-network
      - caddy-network

networks:
  homepage-network:
  caddy-network:
    external: true
