FROM caddy:2.9.1-builder-alpine AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare \
    --with github.com/WeidiDeng/caddy-cloudflare-ip \
    --with github.com/caddyserver/transform-encoder \
    --with github.com/hslatman/caddy-crowdsec-bouncer/http \
    # I don't see a use for them yet.
    # --with github.com/mholt/caddy-l4 \
    # --with github.com/hslatman/caddy-crowdsec-bouncer/appsec@main \
    # --with github.com/hslatman/caddy-crowdsec-bouncer/layer4@main \
    --with github.com/greenpau/caddy-security

FROM caddy:2.9.1

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
